# -*- coding: utf-8 -*-
"""coronary_artery_stenosis_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kTTMPxl4ZKRDjaEZS2X3WNKnXYOUbcZ9
"""

import requests
from tqdm import tqdm

def download_file(url, filename):
    response = requests.get(url, stream=True)

    # Get the total file size
    total_size = int(response.headers.get('content-length', 0))

    # Initialize a progress bar
    progress_bar = tqdm(total=total_size, unit='iB', unit_scale=True)

    with open(filename, 'wb') as file:
        for data in response.iter_content(chunk_size=1024):
            # Write data read to the file
            file.write(data)

            # Update the progress bar
            progress_bar.update(len(data))

    progress_bar.close()

    if total_size != 0 and progress_bar.n != total_size:
        print("ERROR, something went wrong")

# The URL of the file you want to download
url = 'https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/ydrm75xywg-1.zip'

# The path where you want to save the file
filename = '/content/drive/MyDrive/CASD_Dataset/downloaded_file.zip'

download_file(url, filename)

import zipfile

def unzip_file(zip_filepath, dest_dir):
    with zipfile.ZipFile(zip_filepath, 'r') as zip_ref:
        zip_ref.extractall(dest_dir)

# The path of the zip file you want to unzip
zip_filepath = '/content/ydrm75xywg-1/Stenosis detection.zip'

# The directory where you want to extract the zip file
dest_dir = '/content/ydrm75xywg-1/'

unzip_file(zip_filepath, dest_dir)

import shutil

def move_file(src_filepath, dest_filepath):
    shutil.move(src_filepath, dest_filepath)

# The path of the file you want to move
src_filepath = '/content/ydrm75xywg-1/dataset/'  # replace with your file path

# The path where you want to move the file
dest_filepath = '/content/drive/MyDrive/CASD_Dataset/'  # replace with your destination path

move_file(src_filepath, dest_filepath)

